#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ARArt.Android.Resource", IsApplication=true)]

namespace ARArt.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int architectView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int myButton = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int cam = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int compass_accuracy_low = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int device_unsupported = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int hello_world = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int location_fetching = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int main_title_urlLauncher = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int menu_settings = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int poi_description = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int poi_latitude = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int poi_longitude = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int poi_name = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int title_activity_sample1_poi_detail = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int urllauncher_button_launch = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int urllauncher_default_value_textfield = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int urllauncher_hint_textfield = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int urllauncher_menu_clear_history = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
